// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package speedyrest.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

import speedyrest.proxies.constants.Constants;
import speedyrest.services.Cache;
import speedyrest.services.RedisCache;

public class JA_ClearCacheKey extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String key;

	public JA_ClearCacheKey(IContext context, java.lang.String key)
	{
		super(context);
		this.key = key;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Cache redisCache = new RedisCache(
				Constants.getREDIS_HOST(), 
				Constants.getREDIS_PASSWORD(), 
				Constants.getREDIS_PORT().intValue(), 
				Constants.getREDIS_DATABASE_INDEX().intValue());
		return redisCache.deleteByPattern(key);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JA_ClearCacheKey";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
