// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package speedyrest.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import restservices.publish.RestServiceHandler;
import speedyrest.helpers.CacheValidator;
import speedyrest.respositories.CacheRepository;
import speedyrest.usecases.ServeRequestFromCacheHandler;

public class JA_StartSpeedyREST extends CustomJavaAction<java.lang.Boolean>
{
	public JA_StartSpeedyREST(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		CacheValidator cacheValidator = new CacheValidator();
		RestServiceHandler restServiceHandler = new RestServiceHandler();
		CacheRepository cacheRepository = new CacheRepository();
		
		Core.addRequestHandler("srest/", 
				new ServeRequestFromCacheHandler(cacheRepository, cacheValidator, restServiceHandler));
		
		Core.getLogger("SpeedyREST").info("Registered SpeedyREST requesthandler for 'srest/'");
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "JA_StartSpeedyREST";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
